export const READ_EMPLOYES_REQUEST = "READ_EMPLOYES_REQUEST";
export const READ_EMPLOYES_FAILURE = "READ_EMPLOYES_FAILURE";
export const READ_EMPLOYES_SUCCESS = "READ_EMPLOYES_SUCCESS";

export const CHANGE_EMPLOYE_REQUEST = "READ_EMPLOYES_REQUEST";
export const CHANGE_EMPLOYE_FAILURE = "READ_EMPLOYES_FAILURE";
export const CHANGE_EMPLOYE_SUCCESS = "READ_EMPLOYES_SUCCESS";
